version: "3.8"

services:
  mongodb:
    restart: unless-stopped
    image: mongo:latest
    container_name: beats-upload-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}
    networks:
      - socialbeats-network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:7.5.0
  #   container_name: zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - "2181:2181"
  #   networks:
  #     - socialbeats-network

  # kafka:
  #   image: confluentinc/cp-kafka:7.5.0
  #   container_name: kafka
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #   networks:
  #     - socialbeats-network

  beats-upload:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: beats-upload
    environment:
      - MONGOURL=${MONGOURL}
      - MONGOADMIN=${MONGOADMIN}
      - MONGOPASS=${MONGOPASS}
      - NODE_ENV=development
      - PORT=${PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - JWT_SECRET=${JWT_SECRET}
      - API_TITLE=${API_TITLE}
      - API_DESCRIPTION=${API_DESCRIPTION}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - CDN_DOMAIN=${CDN_DOMAIN}
      - CLOUDFRONT_KEY_PAIR_ID=${CLOUDFRONT_KEY_PAIR_ID}
      - CLOUDFRONT_PRIVATE_KEY_BASE64=${CLOUDFRONT_PRIVATE_KEY_BASE64}
      - CLOUDFRONT_URL_EXPIRATION=${CLOUDFRONT_URL_EXPIRATION}
      - KAFKA_CONNECTION_MAX_RETRIES=${KAFKA_CONNECTION_MAX_RETRIES}
      - KAFKA_CONNECTION_RETRY_DELAY=${KAFKA_CONNECTION_RETRY_DELAY}
      - KAFKA_COOLDOWN=${KAFKA_COOLDOWN}
      - KAFKA_BROKER=${KAFKA_BROKER}
      - ENABLE_KAFKA=${ENABLE_KAFKA}
    depends_on:
      - mongodb
      # - kafka
    networks:
      - socialbeats-network
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app:cached
      - /app/node_modules
    command: nodemon --watch /app --legacy-watch --polling-interval 1000 main.js

volumes:
  mongo-data:

networks:
  socialbeats-network:
    external: true