services:
  mongodb:
    restart: unless-stopped
    image: mongo:latest
    container_name: beats-upload-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}
    networks:
      - socialbeats-network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  beats-upload:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beats-upload
    environment:
      - MONGOURL=${MONGOURL}
      - MONGOADMIN=${MONGOADMIN}
      - MONGOPASS=${MONGOPASS}
      - NODE_ENV=production
      - PORT=${PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - JWT_SECRET=${JWT_SECRET}
      - API_TITLE=${API_TITLE}
      - API_DESCRIPTION=${API_DESCRIPTION}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - CDN_DOMAIN=${CDN_DOMAIN}
    depends_on:
      - mongodb
    networks:
      - socialbeats-network
    ports:
      - "${PORT}:${PORT}"

volumes:
  mongo-data:

networks:
  socialbeats-network:
    external: true
